// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBktc-4rempBbYPoAQHPLpA4zM5XPVKtxo',
    appId: '1:1017624062769:web:e7f10080121abf16ef1e10',
    messagingSenderId: '1017624062769',
    projectId: 'wongoji-559ce',
    authDomain: 'wongoji-559ce.firebaseapp.com',
    storageBucket: 'wongoji-559ce.firebasestorage.app',
    measurementId: 'G-L3W7F563MP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOtI02ZP1mG6fd9A6MWenAWBFDA70da9I',
    appId: '1:1017624062769:android:19b3a4263c671f98ef1e10',
    messagingSenderId: '1017624062769',
    projectId: 'wongoji-559ce',
    storageBucket: 'wongoji-559ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaXSNPF1XxCLh4pHKZpD8ZHDcapVlzIJA',
    appId: '1:1017624062769:ios:ab64f671e9d6472cef1e10',
    messagingSenderId: '1017624062769',
    projectId: 'wongoji-559ce',
    storageBucket: 'wongoji-559ce.firebasestorage.app',
    iosClientId: '1017624062769-cpuq083r042rjgqpe68lp27m02ps66e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.wongojiApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaXSNPF1XxCLh4pHKZpD8ZHDcapVlzIJA',
    appId: '1:1017624062769:ios:ab64f671e9d6472cef1e10',
    messagingSenderId: '1017624062769',
    projectId: 'wongoji-559ce',
    storageBucket: 'wongoji-559ce.firebasestorage.app',
    iosClientId: '1017624062769-cpuq083r042rjgqpe68lp27m02ps66e8.apps.googleusercontent.com',
    iosBundleId: 'com.example.wongojiApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBktc-4rempBbYPoAQHPLpA4zM5XPVKtxo',
    appId: '1:1017624062769:web:b8efd38fb5ddc841ef1e10',
    messagingSenderId: '1017624062769',
    projectId: 'wongoji-559ce',
    authDomain: 'wongoji-559ce.firebaseapp.com',
    storageBucket: 'wongoji-559ce.firebasestorage.app',
    measurementId: 'G-YJXG74PP00',
  );
}
